Add setting device name

diff --git a/lib/modules/00_apply_basic_settings b/lib/modules/00_apply_basic_settings
--- a/lib/modules/00_apply_basic_settings
+++ b/lib/modules/00_apply_basic_settings
@@ -1,15 +1,44 @@
 #!/usr/bin/env bash
 
+# Inspiration:
+# https://github.com/bkuhlmann/mac_os-config/blob/main/bin/apply_basic_settings
+
 function apply_basic_settings {
-  printf "NOT IMPLEMENTED YET\n"
+  read -p "What is this machine's label (Example: \"Alchemist\")? " mac_os_label
+  if [[ -z "$mac_os_label" ]]; then
+    printf "ERROR: Invalid MacOS label.\n"
+    exit 1
+  fi
+
+  read -p "What is this machine's name (Example: \"alchemist\")? " mac_os_name
+  if [[ -z "$mac_os_name" ]]; then
+    printf "ERROR: Invalid MacOS name.\n"
+    exit 1
+  fi
+
+  sudo scutil --set ComputerName "$mac_os_label"
+  sudo scutil --set HostName "$mac_os_name"
+  sudo scutil --set LocalHostName "$mac_os_name"
+  sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "$mac_os_name"
+}
+
+function check_basic_settings {
+  printf "CURRENT SETTINGS:\n"
+  printf " ComputerName:  %s\n" "$(scutil --get ComputerName)"
+  printf " HostName:      %s\n" "$(scutil --get HostName)"
+  printf " LocalHostName: %s\n" "$(scutil --get LocalHostName)"
+  printf " NetBIOSName:   %s\n" "$(defaults read /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName)"
+  printf "\n"
 }
 
 function revert_basic_settings {
   printf "NOT IMPLEMENTED YET\n"
+  printf "(I don't know what are the default values)\n"
 }
 
 if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
   printf "Loaded: %s\n" "${BASH_SOURCE[0]}"
 else
+  check_basic_settings
   apply_basic_settings
 fi
